<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание 2: библиотека Numpy и линейная алгебра. Решение


In [2]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.04868665 0.96262356 0.75637153 ... 0.92576514 0.70529656 0.44561415]
 [0.54354348 0.91618924 0.36119163 ... 0.92741541 0.57978816 0.21289267]
 [0.57424999 0.28912857 0.35593505 ... 0.33683854 0.40647041 0.39600269]
 ...
 [0.3174831  0.36636441 0.34726044 ... 0.41392846 0.96372515 0.49499771]
 [0.21493537 0.39298425 0.54687784 ... 0.80822545 0.10876209 0.70660978]
 [0.87714631 0.63873541 0.16757138 ... 0.10237915 0.73091489 0.21981821]]
[[0.92759204 0.7076249  0.37054842 ... 0.68945889 0.99004247 0.67209318]
 [0.46184488 0.79089366 0.58025678 ... 0.4462638  0.64372222 0.31934443]
 [0.15452923 0.98548786 0.36852385 ... 0.01143771 0.30533568 0.92150279]
 ...
 [0.726207   0.93171782 0.30015466 ... 0.56288859 0.66938977 0.98344538]
 [0.96001656 0.83409386 0.44007902 ... 0.09579112 0.84447132 0.35051717]
 [0.2883994  0.86160909 0.67210697 ... 0.72018666 0.11957014 0.86806904]]


In [4]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = [[0 for _ in range(len(a))] for _ in range(len(b[0]))]
    for i in range(len(a)):
        for j in range(len(b)):
            for k in range(len(a[0])):
                c[i][j] += a[i][k] * b[k][j]
    return c

In [5]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return a @ b

In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 730 ms


In [7]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 911 ms


In [8]:
np.abs(np.array(M1) - M2).sum()

1.7674750552032492e-11

### Задание 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [9]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    return np.cumsum(A) / np.arange(1, len(A)+1)

In [10]:
# функция без NumPy
def stupid_sec_av(A):
    S = [sum(A[:i+1])/(i+1) for i in range(len(A))]
    return S

In [11]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# вторая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10**3) 

%time S1 = stupid_sec_av(A)
%time S2 = sec_av(A)
# проверим корректность (последовательности должны совпадать, т.е. разность равна 0):
np.abs(S1 - S2).sum()

Wall time: 68 ms
Wall time: 0 ns


0.0

### Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [12]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    N = np.array(X[::-1])
    N[1::2] = a
    N[::2] = N[::2] ** 3
    return np.hstack((np.array(X) , N))

In [13]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    N = X[::-1]
    N[1::2] = [a for _ in range(len(N[1::2]))]
    N[::2] = [x**3 for x in N[::2]]
    return X + N

In [14]:
X = [i for i in range(10, 1000, 10)]
# здесь код должен быть эффективнее примерно в 20 раз. 
%time S1 = stupid_transformation(X)
%time S2 = transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 0 ns
Wall time: 0 ns


0

Почему методы ***numpy*** оказываются эффективнее (можно гуглить)?

Что вы можете сказать о скорости вычислений в NumPy? Ответ обоснуйте.

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 4

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [15]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.61281824 0.27328172 0.05293099] [0.54471816 0.11774316 0.42830145]


In [16]:
def stupid_scalar_product(a,b):
    return sum([x * y for (x, y) in zip(a, b)])

In [17]:
def numpy_scalar_product(a,b):
    return a @ b

In [18]:
%time product_1 = stupid_scalar_product(a,b)
%time product_2 = numpy_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 190 ms


0.0

### Задание 5*

Нужно написать матричное произведение БЕЗ циклов и БЕЗ символа @, БЕЗ `np.dot` и вообще БЕЗ какой-либо вспомогательной функции из `numpy`, то есть пользуясь только индексированием, взятем суммы по нужным осям и поэлементным произведенем (да, это возможно). Рекомендуем гуглить по запросу "NumPy broadcasting"

In [19]:
def cool_matrix_product(A, B):
    # налейте чаю, удобно присядьте и просто осознайте это :)
    # (на самом деле просто распишите, что получается про numpy broadcasting)
    return (A[:,:, None] * B[None,:,:]).sum(axis=1)  

In [20]:
A = np.random.sample((100, 100))
B = np.random.sample((100, 100))

In [22]:
np.sum(A@B - cool_matrix_product(A, B), axis=0)

array([ 3.19744231e-14, -2.48689958e-14,  3.90798505e-14, -4.97379915e-14,
       -3.19744231e-14,  2.13162821e-14, -2.13162821e-14,  1.77635684e-14,
       -2.48689958e-14,  1.77635684e-14,  3.55271368e-15,  1.06581410e-14,
       -1.42108547e-14, -1.77635684e-14,  4.26325641e-14, -3.55271368e-15,
       -1.77635684e-14,  3.19744231e-14,  2.84217094e-14, -2.13162821e-14,
        1.42108547e-14,  1.42108547e-14, -7.10542736e-15, -3.19744231e-14,
        1.06581410e-14, -3.55271368e-15, -1.06581410e-14, -2.48689958e-14,
       -2.48689958e-14,  1.42108547e-14,  4.97379915e-14,  1.06581410e-14,
       -3.55271368e-15,  6.75015599e-14, -2.84217094e-14, -7.10542736e-14,
       -1.77635684e-14,  2.84217094e-14,  1.06581410e-14,  3.19744231e-14,
        1.42108547e-14, -5.68434189e-14, -1.06581410e-14,  3.19744231e-14,
       -1.42108547e-14,  2.48689958e-14, -5.68434189e-14,  0.00000000e+00,
        2.84217094e-14,  2.48689958e-14, -1.77635684e-14, -3.55271368e-14,
       -2.84217094e-14, -

(машинный ноль)